-- Disable all foreign key constraints before dropping tables
ALTER TABLE ACTION DROP CONSTRAINT FK_ACTION_ROUND;
ALTER TABLE ACTION DROP CONSTRAINT FK_ACTION_ACTING;
ALTER TABLE ACTION DROP CONSTRAINT FK_ACTION_TARGET;

ALTER TABLE ROUND DROP CONSTRAINT FK_ROUND_BATTLE;

ALTER TABLE BATTLE DROP CONSTRAINT FK_BATTLE_WINNER;

ALTER TABLE BATTLE_POKEMON DROP CONSTRAINT FK_BATTLE_POKEMON_BATTLE;
ALTER TABLE BATTLE_POKEMON DROP CONSTRAINT FK_BATTLE_POKEMON_POKEMON;

ALTER TABLE POKEMON_SPECIE DROP CONSTRAINT FK_POKEMON_STAT;

-- Drop tables in reverse order of dependencies
DROP TABLE ACTION CASCADE CONSTRAINTS;
DROP TABLE ROUND CASCADE CONSTRAINTS;
DROP TABLE BATTLE_POKEMON CASCADE CONSTRAINTS;
DROP TABLE BATTLE CASCADE CONSTRAINTS;
DROP TABLE POKEMON_SPECIES CASCADE CONSTRAINTS;
DROP TABLE STAT CASCADE CONSTRAINTS;
DROP TABLE BATTLE_LOG;

DROP PROCEDURE simulate_battle;
DROP PROCEDURE log_action;
DROP FUNCTION calculate_damage;
DROP FUNCTION generate_battle_log;

BEGIN
  -- Delete the schema, if it already exists.
  DBMS_XMLSCHEMA.deleteSchema('BattleLogSchema.xsd',4);
END;