-----------------------------------------------------------------------
-- Delete data and objects script
-----------------------------------------------------------------------
-- Disable all foreign key constraints before dropping tables
ALTER TABLE ACTION DROP CONSTRAINT FK_ACTION_ROUND;
ALTER TABLE ACTION DROP CONSTRAINT FK_ACTION_ACTING;
ALTER TABLE ACTION DROP CONSTRAINT FK_ACTION_TARGET;

ALTER TABLE ROUND DROP CONSTRAINT FK_ROUND_BATTLE;

ALTER TABLE BATTLE DROP CONSTRAINT FK_BATTLE_WINNER;

ALTER TABLE BATTLE_POKEMON DROP CONSTRAINT FK_BATTLE_POKEMON_BATTLE;
ALTER TABLE BATTLE_POKEMON DROP CONSTRAINT FK_BATTLE_POKEMON_POKEMON;

ALTER TABLE POKEMON_SPECIE DROP CONSTRAINT FK_POKEMON_STAT;
ALTER TABLE BATTLE_LOG DROP CONSTRAINT FK_BATTLE_LOG_BATTLE;

-- Drop tables in reverse order of dependencies
DROP TABLE ACTION CASCADE CONSTRAINTS;
DROP TABLE ROUND CASCADE CONSTRAINTS;
DROP TABLE BATTLE_POKEMON CASCADE CONSTRAINTS;
DROP TABLE BATTLE CASCADE CONSTRAINTS;
DROP TABLE POKEMON_SPECIE CASCADE CONSTRAINTS;
DROP TABLE STAT CASCADE CONSTRAINTS;
DROP TABLE BATTLE_LOG;

DROP PROCEDURE LOG_ACTION;
DROP PROCEDURE SIMULATE_BATTLE;
DROP PROCEDURE GENERATE_BATTLE_LOG;

DROP FUNCTION CALCULATE_DAMAGE;
DROP FUNCTION GET_BATTLE_LOG_XSD_VALIDATION;

BEGIN
    -- Delete the schema, if it already exists.
    DBMS_XMLSCHEMA.deleteSchema('BattleLogSchemaV1.xsd',4);
    COMMIT;
END;